apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhel10-bootc-demo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPLACE_WITH_YOUR_GITHUB_REPO_URL
    targetRevision: HEAD
    path: gitops/microshift-app
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
